version: '3'
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33066:${DATABASE_PORT}"
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_PORT=${DATABASE_PORT}
      - MYSQL_HOST=localhost
    volumes:
      - ./db:/var/lib/mysql
  redis:
    image: "redis:alpine"
  django:
    container_name: django
    build: .
    command: "./dbWaitStartDjango.sh"
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    links: 
      - mysql:mysql
      - redis:redis
  celery:
    build: .
    container_name: celery
    command: "./dbWaitStartCelery.sh"
    env_file: .env
    volumes: 
      - .:/app
    depends_on: 
      - django
      - redis
      - mysql
    links: 
      - mysql:mysql
      - redis:redis