# Generated by Django 3.1.7 on 2021-04-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20210410_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='custom_status',
        ),
    ]
