# Generated by Django 3.1.7 on 2021-04-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_profile_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
