# Generated by Django 3.1.7 on 2021-04-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_profile_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_pic.png', upload_to='profile_pics'),
        ),
    ]
